#!/bin/bash

home=$(df -h |  sed -n "10p" | gawk  '{print $5}' | cut -f 1 -d '%')
user=$(du -sk /home/* |  sort -rn | sed -n '2,11p' | gawk '{print $2}' |  sed  's/\/home\///g')

if [ $home -gt 96 ];then
    echo "home 大于 96%"
    echo "$user"
for messages in $user
do
   write $messages</home/liweijie/shell/message.txt
done

else
     echo "home  小于 96%"
fi
